# Generated by Django 5.1 on 2024-09-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_delete_addbook'),
        ('student', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=12)),
                ('return_date', models.CharField(max_length=12)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
