# Generated by Django 5.1 on 2024-09-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_addbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addbook',
        ),
    ]
